apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          readinessProbe: 
            httpGet:
              host: localhost
              path: /
              port: 80 
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 3  
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              host: localhost
              path: /
              port: 80
              scheme: HTTP 
