apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1g
spec: 
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mydata
    type: DirectoryOrCreate
