apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql      
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          envFrom:
            - configMapRef:    #reference for configmap
                name: mysqlconfig
            - secretRef:
                name: mysqlsecret 


