apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP #kubectl get pods -o yaml
            - name: CPULIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: 1m
         
